name: Update Posts

on:
  schedule:
    - cron: "0 0 * * *" # every day at 12:00
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Betiği Çalıştır
        run: |
          deno run -A tools/get_messages_since.ts

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update posts
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STRING_SESSION: ${{ secrets.STRING_SESSION }}
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}